routes:
  /:
    controller: channel
    template: g16-blog
    filter: primary_tag:blog
  /cooperative-chaos/:
    controller: channel
    template: g16-cc
    filter: 'primary_tag:cooperative-chaos'
    data: 'tag.cooperative-chaos'
  /just-streamer-things/:
    controller: channel
    template: g16-jst
    filter: 'primary_tag:just-streamer-things'
    data: 'tag.just-streamer-things'

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: g16-blog
    filter: primary_tag:blog
    data: 'tag.blog'
  /cc/:
    permalink: /cc/{slug}/
    template: g16-cc
    filter: 'primary_tag:cooperative-chaos'
    data: 'tag.cooperative-chaos'
  /jst/:
    permalink: /jst/{slug}/
    template: g16-jst
    filter: 'primary_tag:just-streamer-things'
    data: 'tag.just-streamer-things'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
